### ISSUE TITLE
Call ffmpeg directly

### ISSUE THREAD

**Issue by Moebytes** [FedericoCarboni/eloquent-ffmpeg#13]
### Description
Hi, can you call ffmpeg and ffprobe directly if you don't use `setFFmpegPath`? I don't want to have an additional dependency on `which`, and it's probably faster than searching through all of the executables in my `PATH`.

### Examples
Removes a dependency on which:
```ts
import which from "which"
setFFmpegPath(which.sync("ffmpeg"))
```

### Related Issues
N/A

**Comment by federicocarboni** [comment]
The current implementation for paths is overly complicated for no valid reason; I probably should have come up with a better solution from the start.
You are right: a better approach would be to call `ffmpeg`/`ffprobe` directly by default.
I also think that depending on environmental variables (`FFMPEG_PATH` and `FFPROBE_PATH`) is a bit weird and confusing for the project. `FFMPEG_PATH` and `FFPROBE_PATH` should be removed as well because they don't have much use. Setting FFmpeg's path to `process.env.SOMETHING` is easy enough.

**Comment by Moebytes** [comment]
Thank you! On a side note, thanks a lot for writing this package, it's exactly what I was looking for (being able to pause and resume the ffmpeg process). It was buggy/non-working on `fluent-ffmpeg`, but works perfectly here.

**Comment by federicocarboni** [comment]
I wrote this package mainly because `fluent-ffmpeg` is a very old codebase and it's no longer maintained. Pause/resuming FFmpeg was a must for me, now it should work correctly on Linux, Windows, and macOS. I've actually spent quite some time implementing it for Windows :/
Btw the pull request also removes `setFFmpegPath()` and `setFFprobePath()`: I felt like setting the paths globally didn't really add anything meaningful, so all the functions and methods which spawn FFmpeg have a `ffmpegPath` (or `ffprobePath`) option to override the path per-instance (when not given or `undefined`, `ffmpeg`/`ffprobe` will be called directly). I thought this behavior would be preferable, but let me know.
I'm still developing the package so let me know if you feel like something's missing.
